In [9]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg as LA

In [15]:
def svd(A,k):
    u, s, vt = np.linalg.svd(A, full_matrices=True)
    print(s)
    U = u[:,:k]
    Vt = vt[:k,:]
    S = s[:k]
    sigma = np.diag(S)
    temp = np.matmul(U, sigma)
    Ab = np.matmul(temp, Vt)
    return Ab

In [33]:
def LR(R):
    [n, m] = np.shape(R)
    for j in range(m):
        large = 0
        for i in range(n):
            if (R[i,j]>large):
                large = R[i,j]
        for i in range(n):
            if (R[i,j]==large):
                R[i,j] = i+1
            else :
                R[i,j] = 0
    return R            

In [25]:
temp1 = np.ones(10)
B = np.diag(temp1)
for i in range(9):
    B[i,i+1] = 1
B[8,0] = 1
C = B[:-1,:]
C[0,9] = 1
C

array([[1., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1., 1.]])

In [26]:
f = open('td.txt', "r")
A =  np.genfromtxt(f)

In [27]:
Ab = svd(A,3)

[4.38918841 2.71500921 2.27268558 2.20319289 1.82284038 1.71556485
 1.40428922 0.86852797 0.59355925]


In [34]:
At = np.transpose(A)
Abt = np.transpose(Ab)
print(np.shape(A))
R = np.matmul(At, C)
Rb = np.matmul(Abt, C)
LR(R)

(9, 15)


array([[ 1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  2.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  4.,  4.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  5.,  5.,  5.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  6.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  7.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  9.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [11.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 11.],
       [ 0.,  0.,  0.,  0., 12., 12.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 13.,  0.,  0.,  0.,  0.,  0.,  0.],
       [14.,  0.,  0.,  0.,  0.,  0.,  0., 14., 14., 14.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [35]:
LR(Rb)

array([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  2.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  4.,  4.,  4.,  0.,  4.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [14.,  0.,  0.,  0.,  0., 14.,  0.,  0.,  0., 14.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])